[package]
name = "sea-query-sqlx-mysql-example"
version = "0.1.0"
edition = "2018"

[dependencies]
async-std = "1.8"
sea-query = { path = "../../", features = ["sqlx-mysql"] }
# NOTE: if you are copying this example into your own project, use the following line instead:
# sea-query = { version = "*", features = ["sqlx-mysql"] }

[dependencies.sqlx]
version = "0.5"
default-features = false
features = [
    "runtime-async-std-native-tls",
    "macros",
    "mysql",
    "tls",
]
