[package]
name = "sea-query"
version = "0.1.0"
authors = ["Billy Chan <ccw.billy.123@gmail.com>"]
edition = "2018"
description = "A database agnostic runtime query builder for Rust"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/sea-query"
repository = "https://github.com/SeaQL/Sea-Query"
categories = ["database"]
keywords = ["database", "sql", "mysql", "postgres", "sqlite"]

[dependencies]
serde_json = "1.0"

[dev-dependencies]
async-std = "1.8"
sqlx = { version = "0.4.0-beta.1", default-features = false, features = [ "runtime-async-std", "macros", "any", "mysql", "sqlite", "postgres", "tls", "migrate", "decimal" ] }

[lib]
name = "sea_query"