[package]
name = "sea-query-sqlx-postgres-example"
version = "0.1.0"
edition = "2018"

[dependencies]
async-std = "1.8"
sea-query = { path = "../../", features = ["sqlx-postgres"] }
# NOTE: if you are copying this example into your own repository, use this following line instead:
# sea-query = { version = "*", features = ["sqlx-postgres"] }

[dependencies.sqlx]
version = "0.5"
default-features = false
features = [
    "runtime-async-std-native-tls",
    "macros",
    "postgres",
    "tls",
]
