[package]
name = "sea-query-postgres-json-example"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0"
postgres = "0"
sea-query = { path = "../../", features = ["postgres", "postgres-chrono"] }
# NOTE: if you are copying this example into your own project, use the following line instead:
# sea-query = { version = "*", features = ["postgres", "postgres-chrono"] }
serde_json = "1"